<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260214215559 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE auth_token (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, mode VARCHAR(255) DEFAULT NULL, token VARCHAR(255) DEFAULT NULL, ip VARCHAR(255) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_9315F04EA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE battery (id INT AUTO_INCREMENT NOT NULL, brand VARCHAR(255) DEFAULT NULL, model VARCHAR(255) DEFAULT NULL, capacity DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE battery_price (id INT AUTO_INCREMENT NOT NULL, battery_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, price DOUBLE PRECISION DEFAULT NULL, margin_fixed VARCHAR(50) DEFAULT NULL, start_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', end_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_1336A57B19A19CFC (battery_id), INDEX IDX_1336A57B896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE building (id INT AUTO_INCREMENT NOT NULL, simulation_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, pdl_number VARCHAR(255) DEFAULT NULL, is_customer_certifies_ownership TINYINT(1) DEFAULT NULL, is_agreement_bare_owner TINYINT(1) DEFAULT NULL, INDEX IDX_E16F61D4FEC09103 (simulation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE charging_point (id INT AUTO_INCREMENT NOT NULL, brand VARCHAR(255) DEFAULT NULL, model VARCHAR(255) DEFAULT NULL, power DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE charging_point_price (id INT AUTO_INCREMENT NOT NULL, charging_point_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, price DOUBLE PRECISION DEFAULT NULL, start_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', end_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_DDE376ECAC05B1D8 (charging_point_id), INDEX IDX_DDE376EC896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE company_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) DEFAULT NULL, fullname VARCHAR(255) DEFAULT NULL, is_subject_to_vat TINYINT(1) DEFAULT NULL, map_insee_categories_juridiques LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:simple_array)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer (id INT AUTO_INCREMENT NOT NULL, company_type_id INT DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, civility VARCHAR(10) DEFAULT NULL, firstname VARCHAR(50) DEFAULT NULL, lastname VARCHAR(50) DEFAULT NULL, street_number VARCHAR(30) DEFAULT NULL, street_name VARCHAR(255) DEFAULT NULL, street_location VARCHAR(100) DEFAULT NULL, street_city VARCHAR(255) DEFAULT NULL, street_postcode VARCHAR(20) DEFAULT NULL, street_postbox VARCHAR(50) DEFAULT NULL, street_cedex VARCHAR(50) DEFAULT NULL, phone_number VARCHAR(255) DEFAULT NULL, phone_area_code VARCHAR(20) DEFAULT NULL, foreign_country VARCHAR(255) DEFAULT NULL, foreign_territorial_division VARCHAR(100) DEFAULT NULL, is_agree_receive_email_adm TINYINT(1) DEFAULT NULL, birth_date DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', birth_city VARCHAR(255) DEFAULT NULL, birth_department VARCHAR(255) DEFAULT NULL, birth_country VARCHAR(255) DEFAULT NULL, denomination VARCHAR(255) DEFAULT NULL, company_name VARCHAR(255) DEFAULT NULL, siret VARCHAR(255) DEFAULT NULL, representative_civility VARCHAR(10) DEFAULT NULL, representative_lastname VARCHAR(255) DEFAULT NULL, representative_firstname VARCHAR(255) DEFAULT NULL, can_deduct_vat TINYINT(1) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', customer_type INT DEFAULT NULL, INDEX IDX_81398E09E51E9644 (company_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE doc_category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, sort INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE doc_file (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, user_id INT DEFAULT NULL, path VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, sort INT DEFAULT NULL, groups_can_see JSON DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_D58581C612469DE2 (category_id), INDEX IDX_D58581C6A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE doc_history (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, document_id INT DEFAULT NULL, action INT DEFAULT NULL, done_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_F858F895A76ED395 (user_id), INDEX IDX_F858F895C33F7837 (document_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE file_simulation (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, simulation_id INT DEFAULT NULL, filename VARCHAR(255) DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_72329DCDA76ED395 (user_id), INDEX IDX_72329DCDFEC09103 (simulation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE file_survey (id INT AUTO_INCREMENT NOT NULL, survey_id INT DEFAULT NULL, filename VARCHAR(255) DEFAULT NULL, INDEX IDX_1548BD43B3FE509D (survey_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE file_task (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, task_id INT DEFAULT NULL, filename VARCHAR(255) DEFAULT NULL, added_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', name VARCHAR(255) DEFAULT NULL, INDEX IDX_DB82B34BA76ED395 (user_id), INDEX IDX_DB82B34B8DB60186 (task_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE history (id INT AUTO_INCREMENT NOT NULL, user_id_id INT DEFAULT NULL, simulation_id INT DEFAULT NULL, element VARCHAR(100) DEFAULT NULL, element_id INT DEFAULT NULL, done_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', title VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, INDEX IDX_27BA704B9D86650F (user_id_id), INDEX IDX_27BA704BFEC09103 (simulation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE independent_bonus (id INT AUTO_INCREMENT NOT NULL, nb_panels INT DEFAULT NULL, points DOUBLE PRECISION DEFAULT NULL, points_1 DOUBLE PRECISION DEFAULT NULL, points_2 DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inverter (id INT AUTO_INCREMENT NOT NULL, inverter_cable_id INT DEFAULT NULL, brand VARCHAR(255) DEFAULT NULL, model VARCHAR(255) DEFAULT NULL, power DOUBLE PRECISION DEFAULT NULL, type VARCHAR(1) DEFAULT NULL, electrical_phase VARCHAR(255) DEFAULT NULL, nb_mppt INT DEFAULT NULL, type_inverter VARCHAR(1) DEFAULT NULL, max_input_power DOUBLE PRECISION DEFAULT NULL, nb_string_per_mppt INT DEFAULT NULL, mppt_voltage_range_min INT DEFAULT NULL, mppt_voltage_range_max INT DEFAULT NULL, max_dc_input_voltage INT DEFAULT NULL, is_dc_protection_integrated TINYINT(1) DEFAULT NULL, max_dc_input_current_mppt INT DEFAULT NULL, max_short_circuit_current_mppt INT DEFAULT NULL, INDEX IDX_C9E962C99234EB63 (inverter_cable_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inverter_cable (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inverter_cable_price (id INT AUTO_INCREMENT NOT NULL, inverter_cable_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, price DOUBLE PRECISION DEFAULT NULL, start_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', end_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_562D2C79234EB63 (inverter_cable_id), INDEX IDX_562D2C7896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inverter_price (id INT AUTO_INCREMENT NOT NULL, inverter_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, price DOUBLE PRECISION DEFAULT NULL, start_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', end_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', type VARCHAR(255) DEFAULT NULL, INDEX IDX_A0EC066976223BCF (inverter_id), INDEX IDX_A0EC0669896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE location (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, identifier VARCHAR(50) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, message VARCHAR(255) DEFAULT NULL, url JSON DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_read TINYINT(1) NOT NULL, title VARCHAR(255) DEFAULT NULL, type_notif VARCHAR(50) DEFAULT NULL, INDEX IDX_BF5476CAA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE panel (id INT AUTO_INCREMENT NOT NULL, model VARCHAR(50) DEFAULT NULL, power DOUBLE PRECISION DEFAULT NULL, installation_type VARCHAR(1) DEFAULT NULL, yield_loss_first_year DOUBLE PRECISION DEFAULT NULL, yield_loss_other_years DOUBLE PRECISION DEFAULT NULL, debut_on_sale_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', voltage_open_circuit DOUBLE PRECISION DEFAULT NULL, coef_voc DOUBLE PRECISION DEFAULT NULL, short_circuit_current DOUBLE PRECISION DEFAULT NULL, coef_isc DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE panel_price (id INT AUTO_INCREMENT NOT NULL, panel_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, price DOUBLE PRECISION DEFAULT NULL, start_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', end_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_1A0E31CF6F6FCB26 (panel_id), INDEX IDX_1A0E31CF896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pdl (id INT AUTO_INCREMENT NOT NULL, customer_id INT DEFAULT NULL, temp_customer_id INT DEFAULT NULL, pdl_number VARCHAR(50) NOT NULL, street_number VARCHAR(30) DEFAULT NULL, street_name VARCHAR(255) DEFAULT NULL, street_post_code VARCHAR(20) DEFAULT NULL, street_city VARCHAR(255) DEFAULT NULL, type_compteur VARCHAR(1) DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, building_id VARCHAR(255) DEFAULT NULL, is_customer_certifies_ownership TINYINT(1) DEFAULT NULL, is_agreement_bare_owner TINYINT(1) DEFAULT NULL, INDEX IDX_EE2532929395C3F3 (customer_id), INDEX IDX_EE253292A17B7B37 (temp_customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE permission (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, can_read TINYINT(1) DEFAULT NULL, can_modify TINYINT(1) DEFAULT NULL, can_add TINYINT(1) DEFAULT NULL, maximum_items INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE price (id INT AUTO_INCREMENT NOT NULL, nb_panels INT NOT NULL, price_basic DOUBLE PRECISION NOT NULL, price_discounted_1 DOUBLE PRECISION DEFAULT NULL, price_discounted_2 DOUBLE PRECISION DEFAULT NULL, price_discounted_3 DOUBLE PRECISION DEFAULT NULL, price_discounted_4 DOUBLE PRECISION DEFAULT NULL, installation_type VARCHAR(1) DEFAULT NULL, place VARCHAR(1) DEFAULT NULL, is_eligible_to_bonus TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pricing_factor_condition (id INT AUTO_INCREMENT NOT NULL, pricing_factor_price_id INT DEFAULT NULL, type VARCHAR(100) DEFAULT NULL, value VARCHAR(255) DEFAULT NULL, limit_type VARCHAR(100) DEFAULT NULL, INDEX IDX_4D73EB117CE4D177 (pricing_factor_price_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pricing_factor_price (id INT AUTO_INCREMENT NOT NULL, pricing_factor_id INT DEFAULT NULL, added_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, marked_price DOUBLE PRECISION DEFAULT NULL, unmarked_price DOUBLE PRECISION DEFAULT NULL, start_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', end_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', added_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_3DE3136E1219B519 (pricing_factor_id), INDEX IDX_3DE3136E55B127A4 (added_by_id), INDEX IDX_3DE3136E896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pricing_factor_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE profile (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, description VARCHAR(100) DEFAULT NULL, consumption_rate DOUBLE PRECISION NOT NULL, is_eligible_for_bonus TINYINT(1) DEFAULT NULL, identifier VARCHAR(3) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE role (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE role_permission (role_id INT NOT NULL, permission_id INT NOT NULL, INDEX IDX_6F7DF886D60322AC (role_id), INDEX IDX_6F7DF886FED90CCA (permission_id), PRIMARY KEY(role_id, permission_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seller_bonus (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, simulation_id INT DEFAULT NULL, number DOUBLE PRECISION DEFAULT NULL, INDEX IDX_3F9064C7A76ED395 (user_id), INDEX IDX_3F9064C7FEC09103 (simulation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE signature (id INT AUTO_INCREMENT NOT NULL, content LONGTEXT DEFAULT NULL, firstname_signataire VARCHAR(255) DEFAULT NULL, lastname_signataire VARCHAR(255) DEFAULT NULL, type_signature VARCHAR(10) DEFAULT NULL, is_clause_suspensive TINYINT(1) DEFAULT NULL, birthday DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', birth_place VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE signature_simulation (id INT AUTO_INCREMENT NOT NULL, simulation_id INT DEFAULT NULL, signature_id INT DEFAULT NULL, purpose VARCHAR(255) DEFAULT NULL, INDEX IDX_32DF4CFBFEC09103 (simulation_id), INDEX IDX_32DF4CFBED61183A (signature_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE simulation (id INT AUTO_INCREMENT NOT NULL, owned_by_id INT NOT NULL, panel_id INT DEFAULT NULL, profile_id INT DEFAULT NULL, temp_customer_id INT DEFAULT NULL, customer_id INT DEFAULT NULL, number VARCHAR(255) DEFAULT NULL, identifier VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, consumption_quantity DOUBLE PRECISION DEFAULT NULL, consumption_price DOUBLE PRECISION DEFAULT NULL, reduced_yield DOUBLE PRECISION DEFAULT NULL, price_escalation DOUBLE PRECISION DEFAULT NULL, status INT DEFAULT NULL, installation_price_ht DOUBLE PRECISION DEFAULT NULL, installation_location VARCHAR(1) DEFAULT NULL, is_ardoise_clouee TINYINT(1) DEFAULT NULL, nb_toitures INT DEFAULT NULL, nb_charpentes_non_visibles INT DEFAULT NULL, nb_charpentes_beton INT DEFAULT NULL, final_price_ht DOUBLE PRECISION DEFAULT NULL, manual_price DOUBLE PRECISION DEFAULT NULL, sales_price_escalation DOUBLE PRECISION DEFAULT NULL, reduced_yield_first_year DOUBLE PRECISION DEFAULT NULL, is_force_panel_type TINYINT(1) DEFAULT NULL, installation_street_number VARCHAR(30) DEFAULT NULL, installation_street_name VARCHAR(255) DEFAULT NULL, installation_street_postcode VARCHAR(20) DEFAULT NULL, installation_street_city VARCHAR(255) DEFAULT NULL, is_same_addresses TINYINT(1) DEFAULT NULL, survey_main_building TINYINT(1) DEFAULT NULL, nb_survey_other_buildings INT DEFAULT NULL, signed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', consumption_quantity_detailed JSON DEFAULT NULL, consumption_price_detailed JSON DEFAULT NULL, seasonal_prices TINYINT(1) DEFAULT NULL, subcription_annual_price DOUBLE PRECISION DEFAULT NULL, forced_sales_price DOUBLE PRECISION DEFAULT NULL, estimated_connection_cost DOUBLE PRECISION DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_CBDA467B5E70BCD7 (owned_by_id), INDEX IDX_CBDA467B6F6FCB26 (panel_id), INDEX IDX_CBDA467BCCFA12B8 (profile_id), INDEX IDX_CBDA467BA17B7B37 (temp_customer_id), INDEX IDX_CBDA467B9395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE simulation_battery (id INT AUTO_INCREMENT NOT NULL, simulation_id INT DEFAULT NULL, battery_id INT DEFAULT NULL, quantity INT DEFAULT NULL, price DOUBLE PRECISION DEFAULT NULL, INDEX IDX_5FE73ED5FEC09103 (simulation_id), INDEX IDX_5FE73ED519A19CFC (battery_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE simulation_charging_point (id INT AUTO_INCREMENT NOT NULL, simulation_id INT DEFAULT NULL, charging_point_id INT DEFAULT NULL, quantity INT DEFAULT NULL, price DOUBLE PRECISION DEFAULT NULL, INDEX IDX_ABB9D298FEC09103 (simulation_id), INDEX IDX_ABB9D298AC05B1D8 (charging_point_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE simulation_item (id INT AUTO_INCREMENT NOT NULL, simulation_id INT DEFAULT NULL, pdl_id INT DEFAULT NULL, zone_id INT DEFAULT NULL, building_id INT DEFAULT NULL, nb_panel INT DEFAULT NULL, energy_potential INT DEFAULT NULL, first_year_total_estimated_production DOUBLE PRECISION DEFAULT NULL, detailed_energy_potential JSON DEFAULT NULL, inclinaison INT DEFAULT NULL, azimuth INT DEFAULT NULL, INDEX IDX_DA533D59FEC09103 (simulation_id), INDEX IDX_DA533D593EA22976 (pdl_id), INDEX IDX_DA533D599F2C3FAB (zone_id), INDEX IDX_DA533D594D2A7E12 (building_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE simulation_option (id INT AUTO_INCREMENT NOT NULL, building_id INT DEFAULT NULL, phase_type VARCHAR(50) DEFAULT NULL, add_battery VARCHAR(50) DEFAULT NULL, add_charging_point VARCHAR(50) DEFAULT NULL, installation_location VARCHAR(50) DEFAULT NULL, nb_level VARCHAR(50) DEFAULT NULL, asbestos_roof VARCHAR(50) DEFAULT NULL, nb_roof_section VARCHAR(50) DEFAULT NULL, is_erp_building TINYINT(1) DEFAULT NULL, roof_type VARCHAR(255) DEFAULT NULL, INDEX IDX_F6D2846C4D2A7E12 (building_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE solar_project (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE status (id INT AUTO_INCREMENT NOT NULL, status_group_id INT DEFAULT NULL, name VARCHAR(50) DEFAULT NULL, sort INT DEFAULT NULL, required JSON DEFAULT NULL, color VARCHAR(50) DEFAULT NULL, is_key_step TINYINT(1) NOT NULL, INDEX IDX_7B00651C638E7E9F (status_group_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE status_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) DEFAULT NULL, sort INT DEFAULT NULL, who_can_change JSON NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE status_simulation (id INT AUTO_INCREMENT NOT NULL, simulation_id INT DEFAULT NULL, status_id INT DEFAULT NULL, owned_by_id INT DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', date_event DATETIME DEFAULT NULL, reason_event LONGTEXT DEFAULT NULL, option_selected VARCHAR(255) DEFAULT NULL, INDEX IDX_CA89A2FDFEC09103 (simulation_id), INDEX IDX_CA89A2FD6BF700BD (status_id), INDEX IDX_CA89A2FD5E70BCD7 (owned_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE survey (id INT AUTO_INCREMENT NOT NULL, reviewed_by_id INT DEFAULT NULL, survey_item_id INT DEFAULT NULL, sent_by_id INT DEFAULT NULL, simulation_id INT DEFAULT NULL, content VARCHAR(255) DEFAULT NULL, status_validation VARCHAR(1) DEFAULT NULL, comment VARCHAR(255) DEFAULT NULL, reviewed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_AD5F9BFCFC6B21F1 (reviewed_by_id), INDEX IDX_AD5F9BFC564371E5 (survey_item_id), INDEX IDX_AD5F9BFCA45BB98C (sent_by_id), INDEX IDX_AD5F9BFCFEC09103 (simulation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE survey_item (id INT AUTO_INCREMENT NOT NULL, survey_step_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(50) DEFAULT NULL, options JSON DEFAULT NULL, conditions JSON DEFAULT NULL, INDEX IDX_D9F225D5379E3D27 (survey_step_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE survey_simulation (id INT AUTO_INCREMENT NOT NULL, simulation_id INT DEFAULT NULL, survey_step_id INT DEFAULT NULL, status VARCHAR(1) DEFAULT NULL, comment VARCHAR(255) DEFAULT NULL, status_updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_8EA04C4CFEC09103 (simulation_id), INDEX IDX_8EA04C4C379E3D27 (survey_step_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE survey_step (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, who_can_do JSON NOT NULL, who_can_control JSON DEFAULT NULL, min_project_status INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE task_comment_simulation (id INT AUTO_INCREMENT NOT NULL, added_by_id INT DEFAULT NULL, task_id INT DEFAULT NULL, comment LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_5C08124E55B127A4 (added_by_id), INDEX IDX_5C08124E8DB60186 (task_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE task_simulation (id INT AUTO_INCREMENT NOT NULL, target_user_id INT DEFAULT NULL, simulation_id INT DEFAULT NULL, opened_by_id INT DEFAULT NULL, closed_by_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, target_groups JSON DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', done_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_D7C90DD46C066AFE (target_user_id), INDEX IDX_D7C90DD4FEC09103 (simulation_id), INDEX IDX_D7C90DD4AB159F5 (opened_by_id), INDEX IDX_D7C90DD4E1FA7797 (closed_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE temp_customer (id INT AUTO_INCREMENT NOT NULL, company_type_id INT DEFAULT NULL, firstname VARCHAR(50) DEFAULT NULL, lastname VARCHAR(50) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, phone_number VARCHAR(255) DEFAULT NULL, company_name VARCHAR(255) DEFAULT NULL, company_denomination VARCHAR(255) DEFAULT NULL, siret VARCHAR(255) DEFAULT NULL, street_number VARCHAR(30) DEFAULT NULL, street_name VARCHAR(255) DEFAULT NULL, street_post_box VARCHAR(50) DEFAULT NULL, street_postcode VARCHAR(20) DEFAULT NULL, street_city VARCHAR(255) DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, can_deduct_vat TINYINT(1) DEFAULT NULL, civility VARCHAR(10) DEFAULT NULL, position VARCHAR(255) DEFAULT NULL, representative_civility VARCHAR(10) DEFAULT NULL, representative_firstname VARCHAR(50) DEFAULT NULL, representative_lastname VARCHAR(50) DEFAULT NULL, representative_position VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', customer_type INT DEFAULT NULL, INDEX IDX_E131CAE8E51E9644 (company_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, location_id INT DEFAULT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, civility VARCHAR(10) DEFAULT NULL, lastname VARCHAR(50) DEFAULT NULL, firstname VARCHAR(50) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, picture VARCHAR(255) DEFAULT NULL, date_birthday DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', settings JSON DEFAULT NULL, plain_password VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), INDEX IDX_8D93D64964D218E (location_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_permission (user_id INT NOT NULL, permission_id INT NOT NULL, INDEX IDX_472E5446A76ED395 (user_id), INDEX IDX_472E5446FED90CCA (permission_id), PRIMARY KEY(user_id, permission_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE zone (id INT AUTO_INCREMENT NOT NULL, energy_potential DOUBLE PRECISION NOT NULL, department VARCHAR(10) DEFAULT NULL, panel_tilt VARCHAR(10) DEFAULT NULL, roof_orientation VARCHAR(10) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE auth_token ADD CONSTRAINT FK_9315F04EA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE battery_price ADD CONSTRAINT FK_1336A57B19A19CFC FOREIGN KEY (battery_id) REFERENCES battery (id)');
        $this->addSql('ALTER TABLE battery_price ADD CONSTRAINT FK_1336A57B896DBBDE FOREIGN KEY (updated_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE building ADD CONSTRAINT FK_E16F61D4FEC09103 FOREIGN KEY (simulation_id) REFERENCES simulation (id)');
        $this->addSql('ALTER TABLE charging_point_price ADD CONSTRAINT FK_DDE376ECAC05B1D8 FOREIGN KEY (charging_point_id) REFERENCES charging_point (id)');
        $this->addSql('ALTER TABLE charging_point_price ADD CONSTRAINT FK_DDE376EC896DBBDE FOREIGN KEY (updated_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E09E51E9644 FOREIGN KEY (company_type_id) REFERENCES company_type (id)');
        $this->addSql('ALTER TABLE doc_file ADD CONSTRAINT FK_D58581C612469DE2 FOREIGN KEY (category_id) REFERENCES doc_category (id)');
        $this->addSql('ALTER TABLE doc_file ADD CONSTRAINT FK_D58581C6A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE doc_history ADD CONSTRAINT FK_F858F895A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE doc_history ADD CONSTRAINT FK_F858F895C33F7837 FOREIGN KEY (document_id) REFERENCES doc_file (id)');
        $this->addSql('ALTER TABLE file_simulation ADD CONSTRAINT FK_72329DCDA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE file_simulation ADD CONSTRAINT FK_72329DCDFEC09103 FOREIGN KEY (simulation_id) REFERENCES simulation (id)');
        $this->addSql('ALTER TABLE file_survey ADD CONSTRAINT FK_1548BD43B3FE509D FOREIGN KEY (survey_id) REFERENCES survey (id)');
        $this->addSql('ALTER TABLE file_task ADD CONSTRAINT FK_DB82B34BA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE file_task ADD CONSTRAINT FK_DB82B34B8DB60186 FOREIGN KEY (task_id) REFERENCES task_simulation (id)');
        $this->addSql('ALTER TABLE history ADD CONSTRAINT FK_27BA704B9D86650F FOREIGN KEY (user_id_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE history ADD CONSTRAINT FK_27BA704BFEC09103 FOREIGN KEY (simulation_id) REFERENCES simulation (id)');
        $this->addSql('ALTER TABLE inverter ADD CONSTRAINT FK_C9E962C99234EB63 FOREIGN KEY (inverter_cable_id) REFERENCES inverter_cable (id)');
        $this->addSql('ALTER TABLE inverter_cable_price ADD CONSTRAINT FK_562D2C79234EB63 FOREIGN KEY (inverter_cable_id) REFERENCES inverter_cable (id)');
        $this->addSql('ALTER TABLE inverter_cable_price ADD CONSTRAINT FK_562D2C7896DBBDE FOREIGN KEY (updated_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE inverter_price ADD CONSTRAINT FK_A0EC066976223BCF FOREIGN KEY (inverter_id) REFERENCES inverter (id)');
        $this->addSql('ALTER TABLE inverter_price ADD CONSTRAINT FK_A0EC0669896DBBDE FOREIGN KEY (updated_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE panel_price ADD CONSTRAINT FK_1A0E31CF6F6FCB26 FOREIGN KEY (panel_id) REFERENCES panel (id)');
        $this->addSql('ALTER TABLE panel_price ADD CONSTRAINT FK_1A0E31CF896DBBDE FOREIGN KEY (updated_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE pdl ADD CONSTRAINT FK_EE2532929395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE pdl ADD CONSTRAINT FK_EE253292A17B7B37 FOREIGN KEY (temp_customer_id) REFERENCES temp_customer (id)');
        $this->addSql('ALTER TABLE pricing_factor_condition ADD CONSTRAINT FK_4D73EB117CE4D177 FOREIGN KEY (pricing_factor_price_id) REFERENCES pricing_factor_price (id)');
        $this->addSql('ALTER TABLE pricing_factor_price ADD CONSTRAINT FK_3DE3136E1219B519 FOREIGN KEY (pricing_factor_id) REFERENCES pricing_factor_type (id)');
        $this->addSql('ALTER TABLE pricing_factor_price ADD CONSTRAINT FK_3DE3136E55B127A4 FOREIGN KEY (added_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE pricing_factor_price ADD CONSTRAINT FK_3DE3136E896DBBDE FOREIGN KEY (updated_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE role_permission ADD CONSTRAINT FK_6F7DF886D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE role_permission ADD CONSTRAINT FK_6F7DF886FED90CCA FOREIGN KEY (permission_id) REFERENCES permission (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE seller_bonus ADD CONSTRAINT FK_3F9064C7A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE seller_bonus ADD CONSTRAINT FK_3F9064C7FEC09103 FOREIGN KEY (simulation_id) REFERENCES simulation (id)');
        $this->addSql('ALTER TABLE signature_simulation ADD CONSTRAINT FK_32DF4CFBFEC09103 FOREIGN KEY (simulation_id) REFERENCES simulation (id)');
        $this->addSql('ALTER TABLE signature_simulation ADD CONSTRAINT FK_32DF4CFBED61183A FOREIGN KEY (signature_id) REFERENCES signature (id)');
        $this->addSql('ALTER TABLE simulation ADD CONSTRAINT FK_CBDA467B5E70BCD7 FOREIGN KEY (owned_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE simulation ADD CONSTRAINT FK_CBDA467B6F6FCB26 FOREIGN KEY (panel_id) REFERENCES panel (id)');
        $this->addSql('ALTER TABLE simulation ADD CONSTRAINT FK_CBDA467BCCFA12B8 FOREIGN KEY (profile_id) REFERENCES profile (id)');
        $this->addSql('ALTER TABLE simulation ADD CONSTRAINT FK_CBDA467BA17B7B37 FOREIGN KEY (temp_customer_id) REFERENCES temp_customer (id)');
        $this->addSql('ALTER TABLE simulation ADD CONSTRAINT FK_CBDA467B9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE simulation_battery ADD CONSTRAINT FK_5FE73ED5FEC09103 FOREIGN KEY (simulation_id) REFERENCES simulation (id)');
        $this->addSql('ALTER TABLE simulation_battery ADD CONSTRAINT FK_5FE73ED519A19CFC FOREIGN KEY (battery_id) REFERENCES battery (id)');
        $this->addSql('ALTER TABLE simulation_charging_point ADD CONSTRAINT FK_ABB9D298FEC09103 FOREIGN KEY (simulation_id) REFERENCES simulation (id)');
        $this->addSql('ALTER TABLE simulation_charging_point ADD CONSTRAINT FK_ABB9D298AC05B1D8 FOREIGN KEY (charging_point_id) REFERENCES charging_point (id)');
        $this->addSql('ALTER TABLE simulation_item ADD CONSTRAINT FK_DA533D59FEC09103 FOREIGN KEY (simulation_id) REFERENCES simulation (id)');
        $this->addSql('ALTER TABLE simulation_item ADD CONSTRAINT FK_DA533D593EA22976 FOREIGN KEY (pdl_id) REFERENCES pdl (id)');
        $this->addSql('ALTER TABLE simulation_item ADD CONSTRAINT FK_DA533D599F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id)');
        $this->addSql('ALTER TABLE simulation_item ADD CONSTRAINT FK_DA533D594D2A7E12 FOREIGN KEY (building_id) REFERENCES building (id)');
        $this->addSql('ALTER TABLE simulation_option ADD CONSTRAINT FK_F6D2846C4D2A7E12 FOREIGN KEY (building_id) REFERENCES building (id)');
        $this->addSql('ALTER TABLE status ADD CONSTRAINT FK_7B00651C638E7E9F FOREIGN KEY (status_group_id) REFERENCES status_group (id)');
        $this->addSql('ALTER TABLE status_simulation ADD CONSTRAINT FK_CA89A2FDFEC09103 FOREIGN KEY (simulation_id) REFERENCES simulation (id)');
        $this->addSql('ALTER TABLE status_simulation ADD CONSTRAINT FK_CA89A2FD6BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE status_simulation ADD CONSTRAINT FK_CA89A2FD5E70BCD7 FOREIGN KEY (owned_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE survey ADD CONSTRAINT FK_AD5F9BFCFC6B21F1 FOREIGN KEY (reviewed_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE survey ADD CONSTRAINT FK_AD5F9BFC564371E5 FOREIGN KEY (survey_item_id) REFERENCES survey_item (id)');
        $this->addSql('ALTER TABLE survey ADD CONSTRAINT FK_AD5F9BFCA45BB98C FOREIGN KEY (sent_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE survey ADD CONSTRAINT FK_AD5F9BFCFEC09103 FOREIGN KEY (simulation_id) REFERENCES simulation (id)');
        $this->addSql('ALTER TABLE survey_item ADD CONSTRAINT FK_D9F225D5379E3D27 FOREIGN KEY (survey_step_id) REFERENCES survey_step (id)');
        $this->addSql('ALTER TABLE survey_simulation ADD CONSTRAINT FK_8EA04C4CFEC09103 FOREIGN KEY (simulation_id) REFERENCES simulation (id)');
        $this->addSql('ALTER TABLE survey_simulation ADD CONSTRAINT FK_8EA04C4C379E3D27 FOREIGN KEY (survey_step_id) REFERENCES survey_step (id)');
        $this->addSql('ALTER TABLE task_comment_simulation ADD CONSTRAINT FK_5C08124E55B127A4 FOREIGN KEY (added_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE task_comment_simulation ADD CONSTRAINT FK_5C08124E8DB60186 FOREIGN KEY (task_id) REFERENCES task_simulation (id)');
        $this->addSql('ALTER TABLE task_simulation ADD CONSTRAINT FK_D7C90DD46C066AFE FOREIGN KEY (target_user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE task_simulation ADD CONSTRAINT FK_D7C90DD4FEC09103 FOREIGN KEY (simulation_id) REFERENCES simulation (id)');
        $this->addSql('ALTER TABLE task_simulation ADD CONSTRAINT FK_D7C90DD4AB159F5 FOREIGN KEY (opened_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE task_simulation ADD CONSTRAINT FK_D7C90DD4E1FA7797 FOREIGN KEY (closed_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE temp_customer ADD CONSTRAINT FK_E131CAE8E51E9644 FOREIGN KEY (company_type_id) REFERENCES company_type (id)');
        $this->addSql('ALTER TABLE `user` ADD CONSTRAINT FK_8D93D64964D218E FOREIGN KEY (location_id) REFERENCES location (id)');
        $this->addSql('ALTER TABLE user_permission ADD CONSTRAINT FK_472E5446A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_permission ADD CONSTRAINT FK_472E5446FED90CCA FOREIGN KEY (permission_id) REFERENCES permission (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE auth_token DROP FOREIGN KEY FK_9315F04EA76ED395');
        $this->addSql('ALTER TABLE battery_price DROP FOREIGN KEY FK_1336A57B19A19CFC');
        $this->addSql('ALTER TABLE battery_price DROP FOREIGN KEY FK_1336A57B896DBBDE');
        $this->addSql('ALTER TABLE building DROP FOREIGN KEY FK_E16F61D4FEC09103');
        $this->addSql('ALTER TABLE charging_point_price DROP FOREIGN KEY FK_DDE376ECAC05B1D8');
        $this->addSql('ALTER TABLE charging_point_price DROP FOREIGN KEY FK_DDE376EC896DBBDE');
        $this->addSql('ALTER TABLE customer DROP FOREIGN KEY FK_81398E09E51E9644');
        $this->addSql('ALTER TABLE doc_file DROP FOREIGN KEY FK_D58581C612469DE2');
        $this->addSql('ALTER TABLE doc_file DROP FOREIGN KEY FK_D58581C6A76ED395');
        $this->addSql('ALTER TABLE doc_history DROP FOREIGN KEY FK_F858F895A76ED395');
        $this->addSql('ALTER TABLE doc_history DROP FOREIGN KEY FK_F858F895C33F7837');
        $this->addSql('ALTER TABLE file_simulation DROP FOREIGN KEY FK_72329DCDA76ED395');
        $this->addSql('ALTER TABLE file_simulation DROP FOREIGN KEY FK_72329DCDFEC09103');
        $this->addSql('ALTER TABLE file_survey DROP FOREIGN KEY FK_1548BD43B3FE509D');
        $this->addSql('ALTER TABLE file_task DROP FOREIGN KEY FK_DB82B34BA76ED395');
        $this->addSql('ALTER TABLE file_task DROP FOREIGN KEY FK_DB82B34B8DB60186');
        $this->addSql('ALTER TABLE history DROP FOREIGN KEY FK_27BA704B9D86650F');
        $this->addSql('ALTER TABLE history DROP FOREIGN KEY FK_27BA704BFEC09103');
        $this->addSql('ALTER TABLE inverter DROP FOREIGN KEY FK_C9E962C99234EB63');
        $this->addSql('ALTER TABLE inverter_cable_price DROP FOREIGN KEY FK_562D2C79234EB63');
        $this->addSql('ALTER TABLE inverter_cable_price DROP FOREIGN KEY FK_562D2C7896DBBDE');
        $this->addSql('ALTER TABLE inverter_price DROP FOREIGN KEY FK_A0EC066976223BCF');
        $this->addSql('ALTER TABLE inverter_price DROP FOREIGN KEY FK_A0EC0669896DBBDE');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE panel_price DROP FOREIGN KEY FK_1A0E31CF6F6FCB26');
        $this->addSql('ALTER TABLE panel_price DROP FOREIGN KEY FK_1A0E31CF896DBBDE');
        $this->addSql('ALTER TABLE pdl DROP FOREIGN KEY FK_EE2532929395C3F3');
        $this->addSql('ALTER TABLE pdl DROP FOREIGN KEY FK_EE253292A17B7B37');
        $this->addSql('ALTER TABLE pricing_factor_condition DROP FOREIGN KEY FK_4D73EB117CE4D177');
        $this->addSql('ALTER TABLE pricing_factor_price DROP FOREIGN KEY FK_3DE3136E1219B519');
        $this->addSql('ALTER TABLE pricing_factor_price DROP FOREIGN KEY FK_3DE3136E55B127A4');
        $this->addSql('ALTER TABLE pricing_factor_price DROP FOREIGN KEY FK_3DE3136E896DBBDE');
        $this->addSql('ALTER TABLE role_permission DROP FOREIGN KEY FK_6F7DF886D60322AC');
        $this->addSql('ALTER TABLE role_permission DROP FOREIGN KEY FK_6F7DF886FED90CCA');
        $this->addSql('ALTER TABLE seller_bonus DROP FOREIGN KEY FK_3F9064C7A76ED395');
        $this->addSql('ALTER TABLE seller_bonus DROP FOREIGN KEY FK_3F9064C7FEC09103');
        $this->addSql('ALTER TABLE signature_simulation DROP FOREIGN KEY FK_32DF4CFBFEC09103');
        $this->addSql('ALTER TABLE signature_simulation DROP FOREIGN KEY FK_32DF4CFBED61183A');
        $this->addSql('ALTER TABLE simulation DROP FOREIGN KEY FK_CBDA467B5E70BCD7');
        $this->addSql('ALTER TABLE simulation DROP FOREIGN KEY FK_CBDA467B6F6FCB26');
        $this->addSql('ALTER TABLE simulation DROP FOREIGN KEY FK_CBDA467BCCFA12B8');
        $this->addSql('ALTER TABLE simulation DROP FOREIGN KEY FK_CBDA467BA17B7B37');
        $this->addSql('ALTER TABLE simulation DROP FOREIGN KEY FK_CBDA467B9395C3F3');
        $this->addSql('ALTER TABLE simulation_battery DROP FOREIGN KEY FK_5FE73ED5FEC09103');
        $this->addSql('ALTER TABLE simulation_battery DROP FOREIGN KEY FK_5FE73ED519A19CFC');
        $this->addSql('ALTER TABLE simulation_charging_point DROP FOREIGN KEY FK_ABB9D298FEC09103');
        $this->addSql('ALTER TABLE simulation_charging_point DROP FOREIGN KEY FK_ABB9D298AC05B1D8');
        $this->addSql('ALTER TABLE simulation_item DROP FOREIGN KEY FK_DA533D59FEC09103');
        $this->addSql('ALTER TABLE simulation_item DROP FOREIGN KEY FK_DA533D593EA22976');
        $this->addSql('ALTER TABLE simulation_item DROP FOREIGN KEY FK_DA533D599F2C3FAB');
        $this->addSql('ALTER TABLE simulation_item DROP FOREIGN KEY FK_DA533D594D2A7E12');
        $this->addSql('ALTER TABLE simulation_option DROP FOREIGN KEY FK_F6D2846C4D2A7E12');
        $this->addSql('ALTER TABLE status DROP FOREIGN KEY FK_7B00651C638E7E9F');
        $this->addSql('ALTER TABLE status_simulation DROP FOREIGN KEY FK_CA89A2FDFEC09103');
        $this->addSql('ALTER TABLE status_simulation DROP FOREIGN KEY FK_CA89A2FD6BF700BD');
        $this->addSql('ALTER TABLE status_simulation DROP FOREIGN KEY FK_CA89A2FD5E70BCD7');
        $this->addSql('ALTER TABLE survey DROP FOREIGN KEY FK_AD5F9BFCFC6B21F1');
        $this->addSql('ALTER TABLE survey DROP FOREIGN KEY FK_AD5F9BFC564371E5');
        $this->addSql('ALTER TABLE survey DROP FOREIGN KEY FK_AD5F9BFCA45BB98C');
        $this->addSql('ALTER TABLE survey DROP FOREIGN KEY FK_AD5F9BFCFEC09103');
        $this->addSql('ALTER TABLE survey_item DROP FOREIGN KEY FK_D9F225D5379E3D27');
        $this->addSql('ALTER TABLE survey_simulation DROP FOREIGN KEY FK_8EA04C4CFEC09103');
        $this->addSql('ALTER TABLE survey_simulation DROP FOREIGN KEY FK_8EA04C4C379E3D27');
        $this->addSql('ALTER TABLE task_comment_simulation DROP FOREIGN KEY FK_5C08124E55B127A4');
        $this->addSql('ALTER TABLE task_comment_simulation DROP FOREIGN KEY FK_5C08124E8DB60186');
        $this->addSql('ALTER TABLE task_simulation DROP FOREIGN KEY FK_D7C90DD46C066AFE');
        $this->addSql('ALTER TABLE task_simulation DROP FOREIGN KEY FK_D7C90DD4FEC09103');
        $this->addSql('ALTER TABLE task_simulation DROP FOREIGN KEY FK_D7C90DD4AB159F5');
        $this->addSql('ALTER TABLE task_simulation DROP FOREIGN KEY FK_D7C90DD4E1FA7797');
        $this->addSql('ALTER TABLE temp_customer DROP FOREIGN KEY FK_E131CAE8E51E9644');
        $this->addSql('ALTER TABLE `user` DROP FOREIGN KEY FK_8D93D64964D218E');
        $this->addSql('ALTER TABLE user_permission DROP FOREIGN KEY FK_472E5446A76ED395');
        $this->addSql('ALTER TABLE user_permission DROP FOREIGN KEY FK_472E5446FED90CCA');
        $this->addSql('DROP TABLE auth_token');
        $this->addSql('DROP TABLE battery');
        $this->addSql('DROP TABLE battery_price');
        $this->addSql('DROP TABLE building');
        $this->addSql('DROP TABLE charging_point');
        $this->addSql('DROP TABLE charging_point_price');
        $this->addSql('DROP TABLE company_type');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE doc_category');
        $this->addSql('DROP TABLE doc_file');
        $this->addSql('DROP TABLE doc_history');
        $this->addSql('DROP TABLE file_simulation');
        $this->addSql('DROP TABLE file_survey');
        $this->addSql('DROP TABLE file_task');
        $this->addSql('DROP TABLE history');
        $this->addSql('DROP TABLE independent_bonus');
        $this->addSql('DROP TABLE inverter');
        $this->addSql('DROP TABLE inverter_cable');
        $this->addSql('DROP TABLE inverter_cable_price');
        $this->addSql('DROP TABLE inverter_price');
        $this->addSql('DROP TABLE location');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE panel');
        $this->addSql('DROP TABLE panel_price');
        $this->addSql('DROP TABLE pdl');
        $this->addSql('DROP TABLE permission');
        $this->addSql('DROP TABLE price');
        $this->addSql('DROP TABLE pricing_factor_condition');
        $this->addSql('DROP TABLE pricing_factor_price');
        $this->addSql('DROP TABLE pricing_factor_type');
        $this->addSql('DROP TABLE profile');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE role_permission');
        $this->addSql('DROP TABLE seller_bonus');
        $this->addSql('DROP TABLE signature');
        $this->addSql('DROP TABLE signature_simulation');
        $this->addSql('DROP TABLE simulation');
        $this->addSql('DROP TABLE simulation_battery');
        $this->addSql('DROP TABLE simulation_charging_point');
        $this->addSql('DROP TABLE simulation_item');
        $this->addSql('DROP TABLE simulation_option');
        $this->addSql('DROP TABLE solar_project');
        $this->addSql('DROP TABLE status');
        $this->addSql('DROP TABLE status_group');
        $this->addSql('DROP TABLE status_simulation');
        $this->addSql('DROP TABLE survey');
        $this->addSql('DROP TABLE survey_item');
        $this->addSql('DROP TABLE survey_simulation');
        $this->addSql('DROP TABLE survey_step');
        $this->addSql('DROP TABLE task_comment_simulation');
        $this->addSql('DROP TABLE task_simulation');
        $this->addSql('DROP TABLE temp_customer');
        $this->addSql('DROP TABLE `user`');
        $this->addSql('DROP TABLE user_permission');
        $this->addSql('DROP TABLE zone');
    }
}
